### ISSUE TITLE
Wrong md5 checksum for 2.10 release

### ISSUE THREAD

**Issue by hargobind** [d6lts/backup_migrate#2]
In the process of updating this module on one of my sites via drush make today, I ran into the error `File 6.x-2.10.tar.gz is corrupt (wrong md5 checksum).`

Here's the release history link:
http://updates.mydropwizard.com/files/update/v1/6.x/backup_migrate.xml

Oddly, both the filesize and the checksum in the release history are different than the file in the link above. This is true for both the .tar.gz and the .zip files.

A few other modules (and D6.59) upgraded perfectly fine, but it might be worth checking to see if it's happening elsewhere. And I also confirmed that this isn't an issue for the backup_migrate-6.x-2.9 release.

**Comment by izmeez** [comment]
I can confirm this is an issue:
$ drush --release-backend=mydropwizard dl backup_migrate
File 6.x-2.10.tar.gz is corrupt (wrong md5 checksum).

**Comment by dsnopek** [comment]
Thanks, I've updated the hashes.

But, FYI, this data will be going away soon:

https://www.mydropwizard.com/blog/mydropwizard-closing-down
